version: "3.9"
services:
  mocksensor:
    build: mocksensor #Donde está el Dockerfile
    volumes:
      - ./data/mocksensor:/tmp/
  emqx:
    user: root
    image: "emqx:4.4.3"
    ports:
    - "18083:18083" 
    volumes:
      - ./data/emqx/data:/opt/emqx/data
      - ./data/emqx/log:/opt/emqx/log
    environment:
      - EMQX_DASHBOARD__DEFAULT_USER__LOGIN=luisde2001
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=geled1
  telegrafinput:
    image: "telegraf:1.22.4"
    volumes:
      - ./data/telegrafinput/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./data/mocksensor:/tmp/mocksensor
  influxdb:
    image: "influxdb:2.2.0-alpine"
    ports: 
      - "8086:8086"
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb2
      - ./data/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=luisde2001
      - DOCKER_INFLUXDB_INIT_PASSWORD=geled1geled1
      - DOCKER_INFLUXDB_INIT_ORG=luisde2001
      - DOCKER_INFLUXDB_INIT_BUCKET=iotdata
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=luisde2001-iotdata-auth-token
  telegrafoutput:
    image: "telegraf:1.22.4"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 20
    volumes:
      - ./data/telegrafoutput/telegraf.conf:/etc/telegraf/telegraf.conf
  grafana:
    user: root
    image: "grafana/grafana:8.5.3"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password
    volumes:
      - ./data/grafana:/var/lib/grafana
    secrets:
      - source: grafana_admin_password
        target: /run/secrets/admin_password
secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password